select d.id,
       d.title,
       d.description,
       d.forumID,
       d.siteID,
       d.vanityURL,
       d.pinned,
       d.public,
       d.subscribed,
       d.locked,
       d.status,
       d.products,
       d.tags,
       d.createdAt,
       d.createdBy,
       d.updatedAt,
       d.updatedBy,
       d.requestID,
       d.publishedAt
from edex_discussions.Discussion d;