select sp.id,
       sp.title,
       sp.description,
       sp.vanityURL,
       sp.html,
       sp.css,
       sp.categories,
       sp.isSecure,
       sp.isSearchable,
       sp.status,
       sp.publishedAt,
       sp.createdAt,
       sp.createdBy,
       sp.updatedAt,
       sp.updatedBy,
       sp.siteID,
       sp.requestID,
       sp.wordpressID,
       sp.glueID,
       sp.faqPage,
       sp.products,
       sp.subjects,
       sp.academicLevels,
       sp.isCollection
from edex_staticpage.StaticPage sp;