SELECT m.id, 
       m.adobeGUID,
       m.imsUserId,
       m.imsAuthId,
       m.firstName,
       m.lastName, 
       m.email,
       m.vanityURL,
       m.jobTitle,
       m.city,
       m.regionID,
       m.interests,
       m.experience,
       m.countryCode,
       m.status,
       m.educationSegmentID,
       m.settings,
       m.reputationPoints,
       m.schoolEmail,
       m.schoolEmailVerified,
       m.schoolEmailOrgID,
       m.createdAt
FROM edex_members.Member m;